---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - '_snippets/*'

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  # change the parameter list as query needs a lot of parameters 
  Max: 8