---

development: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"
  DB_FILENAME: db/local/dev.db

test: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"
  DB_FILENAME: db/local/test.db

production: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"